"""initial schema

Revision ID: 1e01e3ddf751
Revises: 
Create Date: 2026-06-06 21:06:00.467086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e01e3ddf751'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intensity_ceiling', sa.Integer(), nullable=False),
    sa.Column('aftercare_prefs', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archetype_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('raw_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_model',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('honorific', sa.String(), nullable=False),
    sa.Column('address_term', sa.String(), nullable=False),
    sa.Column('pronouns', sa.String(), nullable=False),
    sa.Column('archetype_blend', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warmth', sa.Integer(), nullable=False),
    sa.Column('strictness', sa.Integer(), nullable=False),
    sa.Column('sadism', sa.Integer(), nullable=False),
    sa.Column('formality', sa.Integer(), nullable=False),
    sa.Column('verbosity', sa.Integer(), nullable=False),
    sa.Column('crudeness', sa.Integer(), nullable=False),
    sa.Column('wit', sa.Integer(), nullable=False),
    sa.Column('signature_flavor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('denial_timer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economy_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('merit', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACHIEVED', 'ABANDONED', name='goal_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kink_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('kink', sa.String(), nullable=False),
    sa.Column('rating', sa.Enum('FAVORITE', 'LIKE', 'CURIOUS', 'SOFT_LIMIT', 'HARD_LIMIT', 'NA', name='kink_rating'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'kink', name='uq_profile_kink')
    )
    op.create_table('so_context',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('values', sa.String(), nullable=True),
    sa.Column('dynamic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('proof_requirement', sa.Enum('PHOTO', 'VIDEO', 'TIMER', 'HONOR', 'NONE', name='proof_requirement'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merit_reward', sa.Integer(), nullable=False),
    sa.Column('merit_fail_penalty', sa.Integer(), nullable=False),
    sa.Column('merit_miss_penalty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'PROOF_SUBMITTED', 'VERIFYING', 'VERIFIED_PASS', 'VERIFIED_FAIL', 'MISSED', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('intiface_capable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['sub_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toy')
    op.drop_table('task')
    op.drop_table('so_context')
    op.drop_table('kink_entry')
    op.drop_table('goal')
    op.drop_table('economy_state')
    op.drop_table('denial_timer')
    op.drop_table('character_model')
    op.drop_table('archetype_result')
    op.drop_table('sub_profile')
    # ### end Alembic commands ###
    # Postgres does not drop enum types with their tables; drop them explicitly
    # so a downgrade->upgrade round-trip stays clean.
    op.execute("DROP TYPE IF EXISTS task_status")
    op.execute("DROP TYPE IF EXISTS proof_requirement")
    op.execute("DROP TYPE IF EXISTS goal_status")
    op.execute("DROP TYPE IF EXISTS kink_rating")
